// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import CardActionsController from "./card_actions_controller"
application.register("card-actions", CardActionsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SwingerController from "./swinger_controller"
application.register("swinger", SwingerController)

import SwipeController from "./swipe_controller"
application.register("swipe", SwipeController)
